# Generated by Django 4.0.4 on 2022-04-16 04:17

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapterName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CourseName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeTitle', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answerDetails', tinymce.models.HTMLField(default='')),
                ('refDetails', models.CharField(blank=True, max_length=100, null=True)),
                ('answerFIB', models.CharField(blank=True, max_length=100, null=True)),
                ('answerTF', models.CharField(blank=True, max_length=100, null=True)),
                ('optionA', models.CharField(blank=True, max_length=100, null=True)),
                ('optionB', models.CharField(blank=True, max_length=100, null=True)),
                ('optionC', models.CharField(blank=True, max_length=100, null=True)),
                ('optionD', models.CharField(blank=True, max_length=100, null=True)),
                ('answerMCQ', models.CharField(blank=True, max_length=100, null=True)),
                ('marks', models.PositiveIntegerField()),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjectname', to='api.chaptername')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.coursename')),
                ('qType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.questiontype')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coursename', to='api.subjectname')),
            ],
        ),
        migrations.AddField(
            model_name='chaptername',
            name='subjectName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chaptername', to='api.subjectname'),
        ),
    ]
