# Generated by Django 4.0.4 on 2022-05-14 04:58

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questiondata',
            name='answerDetails',
            field=tinymce.models.HTMLField(blank=True, default='', null=True),
        ),
    ]
